name: Test My Action
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run new action
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SEARCH_QUERY: 'org:optimaxdev is:pr author:mik639 author:mkristian1 author:glassesUSA author:Kipicenko author:kkpodolinniy author:VladZhukovOptimax  created:2023-07-01..2023-07-31 -reason:"not planned"'

